### ISSUE TITLE
Camera glitch near Ruined Gallery

### ISSUE THREAD

**Issue by Belokuikuini** [toasterparty/metroid-fool#1]
I've encountered a morph ball camera bug in ruined gallery where the camera would remain completely immobile after morphing.

This happenned after getting in the morph ball tunnel and getting teleported to the map station. Initially, when going back to ruined gallery, the camera would position itself where I assume is the entrance to the morph ball tunnel without the tangle weeds, but still follows Samus by changing angle. This persists after leaving the room, but keeping it loaded. Once the room is unloaded, the camera will not change position nor angle after the morphing animation is complete, even when reloading ruined gallery

I've been able to consistently replicate it by entering the morph ball tunnel, getting teleported to the map station, unmorphing and leaving, and then remorphing. I could also revert the camera back to its functionning state when going back into the ruined gallery tunnel.

Besides that, this hack has been quite the experience so far! Thank you for making this, and I hope this ticket will help improve it :)

**Comment by toasterparty** [comment]
Thanks for the report and glad you've enjoyed the start. I will not be fixing because it's harmless and I think it's funny
